"""
JobShield AI — Real-World Holdout Evaluation

Tests the already-trained model against hand-written examples that were
NOT generated by dataset_generator.py. This is the honest, defensible
accuracy number — separate from the synthetic train/test split.
"""

import os
import sys
import joblib
import numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

# ── Hand-written real-style test set (label: 1 = scam, 0 = legit) ──────────
# Written independently, NOT from dataset_generator.py templates.

TEST_SET = [
    # ── Legit: varied real-world phrasing ──
    ("Hey! We're a 15-person fintech startup in Bangalore looking for a backend dev who knows Django and Postgres. Remote friendly, 6-9 LPA depending on experience. DM me or drop your resume at careers@ourstartup.io", 0),
    ("Placement Cell Notice: Deloitte USI will conduct a pre-placement talk on Thursday 4pm in Seminar Hall 2, followed by online test registration. Eligibility 6.5 CGPA, no active backlogs.", 0),
    ("I'm hiring 2 interns for a 3-month research assistantship under my lab at the university. Unpaid but you'll get a co-authorship credit and LOR. Email your CV to my university address if interested.", 0),
    ("Our QA team is short-staffed and we need someone who can start next week. It's contract-to-hire, 25k/month, fully remote, standup at 10am daily. Reply here if you want a call today.", 0),
    ("Congrats on making it to the final interview round for the Analyst position! Just a heads up, this round is with our VP directly, so dress professionally and expect case-study questions.", 0),
    ("Reminder: your online assessment for the SDE-1 role opens tomorrow 9am and stays open for 48 hours, one attempt only, no negative marking. Good luck.", 0),
    ("We're a small design agency and need a freelance illustrator for a 2-week project, budget 15k, paid 50% upfront via bank transfer after we sign a simple contract, rest on delivery.", 0),
    ("Hi, following up from your campus interview last week - HR will call you tomorrow to discuss the offer letter and joining formalities. No documents or payments needed before that call.", 0),
    ("We just opened 3 spots for our winter internship cohort, unpaid but includes mentorship and a certificate, apply through the Google Form linked in our Instagram bio by Friday.", 0),
    ("Note from HR: background verification for shortlisted candidates will be done through an external agency (not us) and they may call you to confirm employment history. This is a routine step, no fee involved.", 0),
    ("Our recruiter reached out on LinkedIn about a React role, had a proper 45-minute call about the JD, salary band, and next steps. Feels legit, they're sending a formal offer via email next.", 0),
    ("Job Alert: State govt is recruiting Junior Engineers, apply only through the official recruitment board website, exam fee for General category is ₹500 payable via the official portal, no other payment method is valid.", 0),

    # ── Scam: fee-based, varied phrasing ──
    ("Hi dear, your resume has been shortlisted for a work from home job with a reputed MNC. Salary 35k guaranteed. To lock your slot kindly pay Rs 799 registration through the link below.", 1),
    ("SELECTED!! Amazon WFH data entry job, no interview, salary credited daily. Send Rs 500 activation charge to this number to get your ID and start today.", 1),
    ("This is Priya from HR dept, we loved your profile on Indeed, package 45k pm confirmed, just complete KYC by sending Aadhaar photo and paying Rs 999 refundable caution deposit before 6pm today.", 1),
    ("🎉Big opportunity🎉 earn 3000-5000 daily doing simple product review tasks on our app, join our telegram group and pay 1200 joining fee to unlock task assignments, income proof inside group", 1),
    ("Sir/Madam we are conducting online interview for part time typing job, no qualification needed, kindly install this app and deposit Rs 350 as verification amount to receive your first task", 1),

    # ── Scam: newer patterns (task/crypto/investment scams) ──
    ("Congratulations! You've been added to our task group. Complete simple tasks like liking videos and get paid instantly. First 3 tasks are free, after that a small recharge of Rs 600 unlocks higher paying tasks with daily withdrawal.", 1),
    ("Hi, I'm reaching out about a part-time crypto trading assistant role, training provided, guaranteed 8-15% returns weekly, minimum starting investment 2000 to open your trading account with our partner platform.", 1),
    ("Your KYC is pending for salary disbursement, click the link and enter your bank login and OTP to receive your joining bonus of Rs 5000 immediately.", 1),
    ("We are offering online part time jobs, work only 2 hours daily, income upto 25000 monthly, no fee only refundable security which will be returned after 15 successful tasks, register now on WhatsApp.", 1),
    ("Job confirmed! HR will call in 10 mins. Meanwhile please share a screenshot of your bank balance to verify eligibility for the WFH data entry role, this is required by our finance team.", 1),

    # ── Harder / more ambiguous cases ──
    ("Hi, this is regarding the internship you applied for. We do charge a one-time platform fee of Rs 4999 for access to our mentorship portal and placement assistance guarantee, fully non-refundable.", 1),
    ("We're expanding our sales team fast, immediate joining, unlimited earning potential, 100% commission based, no base salary, just bring your own leads and a laptop.", 0),
    ("Selected for the internship! Please note this program does involve a nominal training material fee of Rs 299 which covers your certificate and course access, standard for all our cohorts.", 1),
    ("URGENT hiring for backend intern, only 2 seats left for this batch, apply today, no fee, stipend 12k/month, official college-approved internship via our tie-up with the CS department.", 0),
    ("Thanks for applying! Before we proceed, we just need you to verify your identity by sharing your Aadhaar number and a selfie holding your ID for our records.", 1),
]


def evaluate():
    model_dir = os.path.join(os.path.dirname(__file__), "models")
    tfidf_path = os.path.join(model_dir, "tfidf_vectorizer.pkl")
    model_path = os.path.join(model_dir, "scam_classifier.pkl")

    if not os.path.exists(tfidf_path) or not os.path.exists(model_path):
        print("❌ Trained model not found. Run train_model.py first.")
        return

    tfidf = joblib.load(tfidf_path)
    model = joblib.load(model_path)

    texts = [t.lower().strip() for t, _ in TEST_SET]
    y_true = np.array([label for _, label in TEST_SET])

    X = tfidf.transform(texts)
    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1]

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    print("=" * 55)
    print("📈 REAL-WORLD HOLDOUT EVALUATION (hand-written, unseen)")
    print("=" * 55)
    print(f"  Samples:   {len(TEST_SET)}")
    print(f"  Accuracy:  {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1 Score:  {f1:.4f}")

    print("\n📋 Classification Report:")
    print(classification_report(y_true, y_pred, target_names=["Legitimate", "Scam"]))

    print("🔢 Confusion Matrix:")
    cm = confusion_matrix(y_true, y_pred)
    print(f"  TN={cm[0][0]}  FP={cm[0][1]}")
    print(f"  FN={cm[1][0]}  TP={cm[1][1]}")

    print("\n❌ Misclassified examples:")
    label_name = {0: "Legit", 1: "Scam"}
    for i, (text, true_label) in enumerate(TEST_SET):
        if y_pred[i] != true_label:
            print(f"  True={label_name[true_label]:6s} Pred={label_name[y_pred[i]]:6s} "
                  f"(prob_scam={y_prob[i]:.2f}) | {text[:110]}")

    print("\n✅ Evaluation complete!")


if __name__ == "__main__":
    evaluate()